# Change these first
owner: if-adin # Your GitHub organization or username, where this repository lives
repo: monitoring # The name of this repository

sites:
  - name: GB Matrix
    url: https://matrix.goldenbug.eu
  - name: GB Element
    url: https://element.goldenbug.eu
  - name: GB Dimension
    url: https://dimension.goldenbug.eu
  - name: GB Jitsi
    url: https://jitsi.goldenbug.eu
 
status-website:
  baseUrl: /monitoring # where "repo" is your repository name
  name: Goldenbug status
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "**Goldenbug Status page**"
  introMessage: This is the status page for all Goldenbug services. Matrix is the main server, element is the webclient, jitsi is the voip server, and dimension is the extension manager
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
